CREATE TABLE TIPS (
    tips_id INT AUTO_INCREMENT PRIMARY KEY,
    tips_description TEXT NOT NULL,
    user_id INT NOT NULL,
    tips_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE
);
