CREATE TABLE IF NOT EXISTS NEWSLETTER_SUBSCRIBER (
    subscriber_id INT AUTO_INCREMENT PRIMARY KEY,
    subscriber_email VARCHAR(255) NOT NULL UNIQUE,
    subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
